"""Rich HTML artifact rendering for toxp query results.

Generates a self-contained HTML document via a single additional streaming
LLM call to the same provider used for the coordinator. The model is asked
to author rich visual structure (SVG diagrams, tables, color-coded sections)
rather than just convert markdown to HTML.

This module is pure functions plus one async generator caller — no global
state. Public surface:

    HTML_AUTHOR_SYSTEM_PROMPT
    build_html_author_user_message(result, *, style_hint=None)
    generate_html_artifact(result, *, provider, ...) -> str
    strip_code_fences(text)
    slugify_query(text)
    default_html_path(result, base_dir=None)
    write_html(html, dest)
    open_in_browser(path)
    cleanup_old_html(base_dir, retention_days)
"""

from __future__ import annotations

import os
import re
import unicodedata
import webbrowser
from datetime import datetime, timedelta
from pathlib import Path
from typing import Awaitable, Callable, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from toxp.api import QueryResult
    from toxp.providers.base import BaseProvider


HTML_DIR = Path.home() / ".toxp" / "html"


HTML_AUTHOR_SYSTEM_PROMPT = """You are an expert HTML/CSS designer producing a single self-contained HTML artifact that visually presents the answer to a user's query.

ABSOLUTE OUTPUT RULES (violation breaks the pipeline):
- Output ONLY a complete HTML5 document starting with <!DOCTYPE html>.
- No prose, no commentary, no markdown code fences, no leading/trailing text.
- The document MUST be self-contained: all CSS in a single <style> tag in <head>; any JS inline in <script> tags. No external URLs, no <link rel="stylesheet">, no <script src="...">, no web fonts, no CDN images. The file must render correctly when opened offline.

DESIGN REQUIREMENTS:
- Mobile-responsive: a centered max-width container around 880px with comfortable padding, plus a viewport meta tag.
- Strong typography defaults: a system font stack (-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif), line-height around 1.6, generous reading sizes.
- Semantic HTML: <header>, <main>, <section>, <article>, <footer>.
- A prominent "Final Answer" hero block at the top, with the confidence shown as a pill badge color-coded green=High, amber=Medium, red=Low.
- A subtle agent-stats line near the top (e.g. "12/15 agents succeeded · 47,238 tokens · 38.4s").
- Render the FULL coordinator synthesis (consensus, debates, critique, final answer) as well-organized sections with clear headings and color-coded section accents.
- Tabular data → real <table> with <thead>/<tbody>, zebra rows.
- Where the synthesis describes processes, comparisons, hierarchies, architectures, timelines, or relationships, render an inline <svg> diagram. Keep SVGs simple and legible at the container width. Annotate with text labels.
- Use distinct callout cards for "Consensus" (e.g. green-tinted) vs "Debates" (e.g. amber-tinted).
- Footer with token count, total duration, and a small "Generated by toxp" attribution.

ACCESSIBILITY:
- Sufficient contrast (WCAG AA).
- <title> inside <svg> elements.
- Support both light and dark via `prefers-color-scheme` media query.
"""


_STYLE_HINT_BLOCK_TEMPLATE = "\n\nSTYLE HINT FROM USER: {hint}\n"


def _system_prompt_for(style_hint: Optional[str]) -> str:
    if style_hint and style_hint.strip():
        return HTML_AUTHOR_SYSTEM_PROMPT + _STYLE_HINT_BLOCK_TEMPLATE.format(
            hint=style_hint.strip()
        )
    return HTML_AUTHOR_SYSTEM_PROMPT


def build_html_author_user_message(
    result: "QueryResult",
    *,
    style_hint: Optional[str] = None,
) -> str:
    """Pack the QueryResult into the user message for the HTML pass.

    style_hint is accepted here for API symmetry but the actual hint is
    injected into the system prompt by generate_html_artifact, not here.
    """
    del style_hint  # used at the system-prompt layer

    query_text = ""
    if result.raw_result is not None:
        query_text = result.raw_result.query.text

    duration = result.total_duration_seconds
    return (
        f"QUERY:\n{query_text}\n\n"
        f"CONFIDENCE: {result.confidence}\n"
        f"AGENT STATS: {result.successful_agents}/{result.total_agents} agents · "
        f"{result.total_tokens:,} tokens · {duration:.1f}s\n\n"
        f"FINAL ANSWER:\n{result.final_answer}\n\n"
        f"CONSENSUS SUMMARY:\n{result.consensus_summary}\n\n"
        f"KEY DEBATES:\n{result.debates_summary}\n\n"
        f"FULL COORDINATOR SYNTHESIS (markdown):\n{result.synthesis_markdown}\n"
    )


_FENCE_OPEN_RE = re.compile(r"^\s*```(?:html|HTML)?\s*\n", re.MULTILINE)
_FENCE_CLOSE_RE = re.compile(r"\n\s*```\s*$")


def strip_code_fences(text: str) -> str:
    """Remove a leading ```html / ``` and trailing ``` if the model wrapped output."""
    out = text
    m = _FENCE_OPEN_RE.match(out)
    if m:
        out = out[m.end():]
        out = _FENCE_CLOSE_RE.sub("", out)
    return out.strip()


def _looks_like_html(text: str) -> bool:
    head = text.lstrip()[:32].lower()
    return head.startswith("<!doctype") or head.startswith("<html")


class HtmlGenerationError(RuntimeError):
    """Raised when the HTML pass produces output that is not a valid HTML document."""


async def generate_html_artifact(
    result: "QueryResult",
    *,
    provider: "BaseProvider",
    style_hint: Optional[str] = None,
    on_token: Optional[Callable[[str], None]] = None,
    temperature: float = 0.7,
    max_tokens: int = 16384,
) -> str:
    """Stream the HTML-author LLM call, return the cleaned HTML string.

    Raises HtmlGenerationError if the output, after fence-stripping, doesn't
    start with <!DOCTYPE or <html.
    """
    system_prompt = _system_prompt_for(style_hint)
    user_message = build_html_author_user_message(result)

    chunks: list[str] = []
    stream = provider.invoke_model_stream(
        system_prompt=system_prompt,
        user_message=user_message,
        temperature=temperature,
        max_tokens=max_tokens,
    )
    async for token in stream:
        chunks.append(token)
        if on_token is not None:
            on_token(token)

    raw = "".join(chunks)
    cleaned = strip_code_fences(raw)
    if not cleaned:
        raise HtmlGenerationError("HTML pass produced empty output")
    if not _looks_like_html(cleaned):
        preview = cleaned[:80].replace("\n", " ")
        raise HtmlGenerationError(
            f"HTML pass output does not look like HTML (starts with: {preview!r})"
        )
    return cleaned


_SLUG_NON_ALNUM_RE = re.compile(r"[^a-z0-9]+")


def slugify_query(text: str, *, max_len: int = 48) -> str:
    """Lowercase, ASCII-only, hyphen-separated. Empty/punct-only input -> 'query'."""
    if not text:
        return "query"
    normalized = unicodedata.normalize("NFKD", text)
    ascii_only = normalized.encode("ascii", "ignore").decode("ascii")
    lowered = ascii_only.lower()
    slug = _SLUG_NON_ALNUM_RE.sub("-", lowered).strip("-")
    if not slug:
        return "query"
    if len(slug) > max_len:
        slug = slug[:max_len].rstrip("-")
        if not slug:
            return "query"
    return slug


def default_html_path(
    result: "QueryResult",
    base_dir: Optional[Path] = None,
) -> Path:
    """Build ~/.toxp/html/<YYYY-MM-DD_HHMMSS>-<slug>.html for this result."""
    base = base_dir if base_dir is not None else HTML_DIR
    if result.raw_result is not None:
        ts = result.raw_result.query.timestamp
        slug = slugify_query(result.raw_result.query.text)
    else:
        ts = datetime.now()
        slug = "query"
    filename = f"{ts:%Y-%m-%d_%H%M%S}-{slug}.html"
    return base / filename


def write_html(html: str, dest_path: Path) -> Path:
    """Atomically write `html` to dest_path. Returns dest_path."""
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = dest_path.with_suffix(dest_path.suffix + ".tmp")
    tmp_path.write_text(html, encoding="utf-8")
    os.replace(tmp_path, dest_path)
    return dest_path


def open_in_browser(path: Path) -> bool:
    """Open `path` in the user's default browser via webbrowser.open."""
    return webbrowser.open(f"file://{path.resolve()}")


def cleanup_old_html(base_dir: Path, retention_days: int) -> int:
    """Delete *.html in base_dir older than retention_days. Returns count deleted."""
    if not base_dir.exists():
        return 0
    cutoff = datetime.now() - timedelta(days=retention_days)
    deleted = 0
    for html_file in base_dir.glob("*.html"):
        try:
            mtime = datetime.fromtimestamp(html_file.stat().st_mtime)
            if mtime < cutoff:
                html_file.unlink()
                deleted += 1
        except (OSError, ValueError):
            continue
    return deleted


# Some callers (e.g. the CLI try/except) want a ready-to-await coroutine
# that returns Optional[str] instead of raising. Kept thin and explicit.
async def safe_generate(
    result: "QueryResult",
    *,
    provider: "BaseProvider",
    style_hint: Optional[str] = None,
    on_token: Optional[Callable[[str], None]] = None,
    temperature: float = 0.7,
    max_tokens: int = 16384,
) -> tuple[Optional[str], Optional[Exception]]:
    """generate_html_artifact wrapper that returns (html, error) instead of raising."""
    try:
        html = await generate_html_artifact(
            result,
            provider=provider,
            style_hint=style_hint,
            on_token=on_token,
            temperature=temperature,
            max_tokens=max_tokens,
        )
        return html, None
    except Exception as exc:  # noqa: BLE001 — caller decides what to do with it
        return None, exc


__all__ = [
    "HTML_AUTHOR_SYSTEM_PROMPT",
    "HtmlGenerationError",
    "build_html_author_user_message",
    "cleanup_old_html",
    "default_html_path",
    "generate_html_artifact",
    "open_in_browser",
    "safe_generate",
    "slugify_query",
    "strip_code_fences",
    "write_html",
]


# Silence unused-import warnings for typing-only imports (keeps mypy happy).
_ = (Awaitable,)
